spring.application.name=apis-externas
#spring.datasource.url=jdbc:postgresql://localhost:5432/bdjava14
#spring.datasource.username=postgres
#spring.datasource.password=admin
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.servlet.context-path=/apis/codigo
#server.port=8082
server.port=${PORT:8082}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#postgresql://neondb_owner:npg_BEtrCDheM25W@ep-bold-king-acsdb3wo-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
#decoleta.token=sk_13418.psSRgwTWR1b0oTq5I8tSVVQ4JDNWTilF
#decoleta.base-url:https://api.decolecta.com
decoleta.token=${DECOLETA_TOKEN}
decoleta.base-url:${DECOLETA_BASE_URL}
#sk_7701.y0uLrT7FJyzCkN2zotD3R23j02ZMYoRU
#sk_13418.psSRgwTWR1b0oTq5I8tSVVQ4JDNWTilF

spring.application.admin.enabled=false

logging.level.root=info

#mock.base-url=http://localhost:8080
mock.base-url=${MOCK_BASE_URL://localhost:8080}
spring.cloud.openfeign.client.config.mockClient.connectTimeout=8000
spring.cloud.openfeign.client.config.mockClient.readTimeout=8000